### ISSUE TITLE
ToDo [twitter-image-search-app]

### ISSUE THREAD

**Issue by Yagami360** [Yagami360/react-app-exercise#1]
## 全体
- [x] ダークモード機能
    - [x] ダークモードにすると入力フォームが見えなくなるバグの修正 
    - [x] アイコン色の調整
    - [x] 背景もダークモードになるようにする
    - [x] ダークモード切替時にページリロードしなくても即座に反映するようにする
    - [ ] ダークモード状態をローカルディスクではなく firestore に保存するようにする
- [ ] Twiter API v2 への対応
- [x] 各種コンフィグ値を１つのファイルで一元管理するように修正
- [x] プロジェクトをビルドして外部公開
- [x] アプリを公開する際には Firestore を本番モードで運用（テストモードだと３０日でアクセス不可になるため）
    - [ ] アクセス可能なユーザーを制限する
- [ ] Twitter API の利用上限に達すると、自動的に別の API キーを使用してリクエストする機能

## ヘッダー
- [x] メニューバーから各ページ（「お気に入り」ページ、「設定」ページ）に移動出来るようにする
- [x] ヘッダーのタブから各ページ（「お気に入り」ページ、「設定」ページ）に移動出来るようにする
   - [x] スタイルの調整
   - [x] メニュー画面からページ移動されたときにタブの選択状態が反映されないバグの修正
- [x] 右上アイコンでログイン機能
  - [x] ログインアイコンが消えるバグ修正 → リロード直後にログイン中であっても `auth.currentUser=null` になる問題への対処）
      - https://zenn.dev/phi/articles/firebase-auth-wait-for-initialization
- [x] 右上アイコンでログアウト機能

## トップページ
- [x] 検索履歴表示機能
  - [x]  履歴をマスクで選択すると検索ワードのステートに反映されないバグの修正
- [x] 検索ヒット数が少ない問題の修正。繰り返し検索
  - https://blog.apar.jp/php/3007/
- [ ] 無限スクロール機能追加（検索結果を部分的に表示する機能）
- [x] プロフィールとツイートの AND 検索機能
  - [ ] Twitter API の `'users/search'` だとプロフィールに含まれる検索ワードでの検索ができていないので、別の API 検討？
- [ ] 検索履歴のクリア機能
- [ ] 検索中のプログレスバーの表示

## 画像検索ページ
- [x] 検索ヒット数が少ない問題の修正。繰り返し検索
    - https://qiita.com/ryo-a/items/53fe9eadcf719b817c9a
- [x] 無限スクロール機能追加（検索結果を部分的に表示する機能）
- [ ] 検索履歴のクリア機能
- [ ] 検索中のプログレスバーの表示
- [ ] 右上ボタンで画像サイズ（小・中・大）を変更出来るようにする
- [ ] RT での画像付きツイートを除外する

## プロフィール検索ページ
- [x] プロフィールの TwitterCard 表示
- [x] 検索ヒット数が少ない問題の修正。繰り返し検索
- [ ] 検索履歴のクリア機能
- [ ] 検索中のプログレスバーの表示
- [x] 無限スクロール機能追加

## タイムラインページ
- [x] フォロー＆タイムライン表示機能
  - [x] 全フォローユーザーのツイートを時系列でタイムライン表示する列レイアウト
     - [x] 時系列順になったりならなかったりするバグの修正
  - [x] 各フォローユーザーのツイートを時系列でタイムライン表示する列レイアウト
- [x] レイアウトの調整
- [x] ドラック＆ドロップ機能
    - [x] ドラック＆ドロップで表示順を変更できるようにする
    - [ ] 先頭にしかドラック＆ドロップできないバグの修正
    - [ ] ドラック＆ドロップで変更した表示順を保存する
- [ ] リストフォルダ機能
    - [ ] 複数のフォローユーザーをリスト管理して表示する機能
- [x] 画像ツイートがないユーザーのタイムラインを表示しないようにする（タイムラインの列を確保しない）
- [ ] 右上ボタンで画像サイズ（小・中・大）を変更出来るようにする
- [x] 検索ヒット数が少ない問題の修正。繰り返し検索
    - [ ] レスポンスされたツイートの最後の配列要素の id 値を max_id として再帰的に処理すると前回のリクエストの最後のツイートが２回表示されてしまう問題の修正
- [x] 各ユーザーのタイムラインツイート度に下方向スクロールできるようにする
- [ ] 無限スクロール機能追加（検索結果を部分的に表示する機能）
    - [ ] 全ユーザーのタイムラインツイートの無限スクロール機能
    - [ ] 各ユーザーのタイムラインツイートの無限スクロール機能
- [x] 一部のフォローユーザーのタイムラインしか表示されないバグの修正

## お気に入りページ
- [x] ☆ボタンクリック時のお気に入り保存機能
- [ ] お気に入り状態をローカルディスクではなく firebase のデータベースに保存するように修正
- [x] ドラック＆ドロップ機能
    - [x] ドラック＆ドロップで表示順を変更できるようにする
    - [ ] 先頭か終端にしかドラック＆ドロップできないバグの修正
    - [ ] ドラック＆ドロップ時にドラック中以外のカードが下に移動するバグの修正
    - [ ] ドラック＆ドロップで変更した表示順を保存する
- [ ] お気に入りフォルダ機能
    - [ ] ドラック＆ドロップでエクスプローラ的にフォルダ操作出来るようにする
- [ ] 右上ボタンで画像サイズ（小・中・大）を変更出来るようにする

## 設定ページ
- [ ] xxx
